spring:
  jwt:
    secret: HelloMyNickNameIsBeHangAndNiceToMeetYouHowAreYouImFineThankYouAndYou


auth:
  naver:
    client-id: ooo
    client-secret: ooo
  kakao:
    client-id: ooo
    client-secret: ooo