spring:
  jwt:
    secret: HelloMyNickNameIsBeHangAndNiceToMeetYouHowAreYouImFineThankYouAndYou


auth:
  naver:
    client-id: ooo
    client-secret: ooo
  kakao:
    rest_api_key: c60eda1ceb691b855e628903c94da968
  openapi:
    serviceKey: 6VuSWL7hrdd5tfkipCx%2Btcr7kPla0Vk%2BZCx3li0tAyftAak75s1%2Bova46Svl3BwONWv1wbFLZ0Xkm8g1KljxmA%3D%3D