spring:
  jwt:
    secret: HelloMyNickNameIsBeHangAndNiceToMeetYouHowAreYouImFineThankYouAndYou


auth:
  naver:
    client-id: CmSvvZFnw1WCzjqSq5dQ
    client-secret: zXn_Mxth_5
  kakao:
    client-id: ooo
    client-secret: ooo