spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/orgo_prod?validationQuery="select 1"&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: produser
    password: orgo1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: select 1 from dual
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        enable_lazy_load_no_trans: true
        format_sql: true
        hbm2ddl:
          auto: validate
    show-sql: true

orgo-server:
  address: http://34.64.36.223
  path:
    storage:
      images: /orgo/resources/images